# -*- coding: utf-8 -*-
"""Medical_Insurance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OaamG6UovGXUSyrKbxTYNvaPwuXj1Jaf
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

insu=pd.read_csv("/content/medical_insurance.csv")

insu.isnull().sum()

insu.head()

from sklearn.preprocessing import LabelEncoder

LR=LabelEncoder()

insu['Gender']=LR.fit_transform(insu['sex'])

insu['soking']=LR.fit_transform(insu['smoker'])

insu['stay']=LR.fit_transform(insu['region'])

insu.tail(5)

age=int(input("enter your age"))
sex=int(input("if female enter 0,if male enter 1  "))
bmi=float(input("body mass index"))
child=int(input("how many child you have"))
smo=int(input("if you smoke enter 1 otherwise enter 0  "))
reg=int(input("southwest=3,southeast=2,northwest=1  "))
pay=float(input("enter your fees"))

indep=insu[['age','Gender','bmi','children','soking','stay']]
dep=insu['charges']

lr.fit(indep,dep)

lr.predict([[45,1,50,2,1,2]])

lr.predict([[age,sex,bmi,child,smo,reg]])